---
#- name: Setting up hostname
- hosts: all
  order: sorted
  gather_facts: False
  tasks:
    - hostname:
        name: demo-ops

    - name : Creating a user called demo
      user: 
        name: demo

    - sysctl:
        name: vm.swappiness
        value: '5'
        state: present
    - sysctl:
        name: fs.file-max
        value: '500000'
        state: present
    - sysctl:
        name: kernel.panic
        state: present
        sysctl_file: /etc/sysctl.conf
      

    - name: Setting timezone to Asia/Kolkata
      timezone:
        name: Asia/Kolkata

    - name: Install docker packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Add Docker s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Set up the stable repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        state: present
        update_cache: yes

    # sudo apt-get update
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install docker
      apt:
        name: docker-ce=19.03.*
        state: present
        update_cache: yes
      notify: Start docker on boot

    - name: Create "docker" group
      group:
        name: "docker"
        state: present

    - name: Add remote "ubuntu" user to "docker" group
      user:
        name: "ubuntu"
        group: "docker"
        append: yes

    - name: Install docker-compose
      apt:
        name: docker-compose=1.25.*
        state: present
        update_cache: yes

    - name: Copy  docker-compose.yml to /etc/demo-ops
      copy:
        src: docker-compose.yml
        dest: /etc/demo-ops
        
    - name: Run docker-compose file 
      command: docker-compose -f /etc/demo-ops/docker-compose.yml up -d


...